name: Create and publish a Docker image

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx        
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Registry        
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build & Push Docker image
        run: docker buildx build -t ghcr.io/mortyn/piclustermetrics:${GITHUB_SHA} -f ./Dockerfile --push --platform=linux/arm64,linux/amd64 .
        
      - name: Bump AppVersion
        env:
          HelmRepo: MortyN/helm-repo
          ChartLocation: charts/piclustermetrics/Chart.yaml
          AppVersion: ${{ github.sha }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: ${{ secrets.ACTIONS_PAT_KEY }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.HelmRepo }}/dispatches \
          -d '{"event_type":"bump_appversion","client_payload":{"appversion": "${{ env.AppVersion }}", "helmchartdir": "${{ env.ChartLocation }}"}}'
